version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_progreso2
    ports:
      - "5672:5672"   # Puerto estándar de RabbitMQ
      - "15672:15672" # Interfaz de administración web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
